parser: babel-eslint

parserOptions:
  sourceType: module

plugins:
  - babel

rules:
  # https://github.com/babel/babel-eslint/issues/554
  quotes: off
  babel/quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  # the default 'semi' rule does not check class properties
  semi: off
  babel/semi:
    - error
    - always

