parser: '@babel/eslint-parser'

parserOptions:
  sourceType: module

plugins:
  - babel

rules:
  babel/quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  # the default 'semi' rule does not check class properties
  semi: off
  babel/semi:
    - error
    - always
